version: '3'

services:
  finbot:
    build:  
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - NAME=${NAME:-devUser}
    tty: true
    environment:
      - DB_USER=${DB_USER}
      - DB_USER_PW=${DB_USER_PW}
    volumes:
      - ${WORKSPACE_PATH:-..}:/workspace:cached
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.9.5
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PW}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ${PWD}/.deploy/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ${PWD}/mariadb:/var/lib/mysql:rw

networks:
  default:
    name: kfa-dev-network