version: '3'

services:
  finbot:
    container_name: finBOT
    build:  
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - NAME=${NAME:-devUser}
    tty: true
    volumes:
      - ${WORKSPACE_PATH:-..}:/workspace:cached
      - ${WORKDIR}/data:/workspace/data:rw