CREATE DATABASE IF NOT EXISTS `finbot`;
USE `finbot`;

CREATE TABLE IF NOT EXISTS `player` (
    `id` INT UNSIGNED AUTO_INCREMENT,
    `username` VARCHAR(255) NOT NULL,
    `fincount` INT NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `mapfin` (
    `id` INT UNSIGNED AUTO_INCREMENT,
    `mapname` VARCHAR(255) NOT NULL,
    `score` INT UNSIGNED NOT NULL,
    `date` TIMESTAMP NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `player_id` INT UNSIGNED NOT NULL,
    `delta` INT UNSIGNED NULL,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`player_id`) REFERENCES `player` (`id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT
) ENGINE = InnoDB;