version: '3'

services:
  finbot:
    container_name: finBOT
    build:  
      context: ..
      dockerfile: .deploy/Dockerfile
      args:
        - UID=${UID}
        - GID=${GID}
        - NAME=${NAME}
    volumes:
      - ${WORKDIR}:/workspace:cached
      - ${WORKDIR}/data:/workspace/data:rw
    restart: "unless-stopped"
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"